"""add new attribute to solution

Revision ID: 046120a5a056
Revises: cc9a981f0109
Create Date: 2018-11-09 08:49:03.178643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '046120a5a056'
down_revision = 'cc9a981f0109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solution', sa.Column('unique_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solution', 'unique_name')
    # ### end Alembic commands ###
