"""add new attribute to solution

Revision ID: 2aa40c4cdc5a
Revises: 046120a5a056
Create Date: 2018-11-09 09:23:09.262924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aa40c4cdc5a'
down_revision = '046120a5a056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solution', sa.Column('name', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solution', 'name')
    # ### end Alembic commands ###
