"""add new attribute

Revision ID: cc9a981f0109
Revises: 8061f8c0f16a
Create Date: 2018-11-09 08:10:21.259963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc9a981f0109'
down_revision = '8061f8c0f16a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homework', sa.Column('unique_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('homework', 'unique_name')
    # ### end Alembic commands ###
